name: Main Action

on:
  push: 
    branches: 
      - main
      
jobs:
  release:
    name: Create Release Changelog
    if: startsWith(github.event.head_commit.message, 'feat') || startsWith(github.event.head_commit.message, 'fix') || startsWith(github.event.head_commit.message, 'docs') || startsWith(github.event.head_commit.message, 'style') || startsWith(github.event.head_commit.message, 'refactor') || startsWith(github.event.head_commit.message, 'perf') || startsWith(github.event.head_commit.message, 'test') || startsWith(github.event.head_commit.message, 'build') || startsWith(github.event.head_commit.message, 'ci') || startsWith(github.event.head_commit.message, 'chore') || startsWith(github.event.head_commit.message, 'revert') 
    uses: ./.github/workflows/release.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
   
 # merge:
  #  name: merge
   # if: github.event_name == 'pull_request'             
   # needs:
   #   - release
   # uses: ./.github/workflows/merge.yml
   # secrets:
   #   RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-docs:
    name: build docs
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') 
    uses: ./.github/workflows/docs.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      
  update-docs:
    name: update docs
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'Update')
    uses: ./.github/workflows/docs.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}


  test:
    name: Test
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'mytest')
    uses: ./.github/workflows/test.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      
      
      
      